
const products = [
{ label: "Application", value: "Art & Collectible", checkoutType: "pastura" },
{ label: "Brand Name", value: "No", checkoutType: "pastura" },
{ label: "Color", value: "Customized Color", checkoutType: "pastura" },
{ label: "Delivery time", value: "40–45 Days", checkoutType: "pastura" },
{ label: "Feature", value: "Artistic", checkoutType: "pastura" },
{ label: "Logo", value: "Customized Logo", checkoutType: "pastura" },
{ label: "MOQ", value: "200pcs", checkoutType: "pastura" },
{ label: "Material", value: "Resin, Polyresin", checkoutType: "pastura" },
{ label: "Model Number", value: "NO", checkoutType: "pastura" },
{ label: "Packing", value: "PP bag + white box + outdoor box", checkoutType: "pastura" },
{ label: "Pattern", value: "SCULPTURE", checkoutType: "pastura" },
{ label: "Payment", value: "T/T, PayPal, Western Union", checkoutType: "pastura" },
{ label: "Place of Origin", value: "Fujian, China", checkoutType: "shopify" },
{ label: "Product Type", value: "Figurine", checkoutType: "pastura" },
{ label: "Sample Time", value: "7–15 days", checkoutType: "pastura" },
{ label: "Shape", value: "Irregular", checkoutType: "pastura" },
{ label: "Size", value: "Customized Size", checkoutType: "pastura" },
{ label: "Style", value: "Decoration", checkoutType: "pastura" },
{ label: "Technique", value: "Hand-painted", checkoutType: "pastura" },
{ label: "Usage", value: "Decoration", checkoutType: "pastura" },
{
  "title": "90% Coffee-Color Shade Cloth Sunshade Net",
  "description": "Durable HDPE shade cloth blocks 90% sunlight to protect gardens, patios, greenhouses, and plant canopies. Easy to install and weather-resistant for year-round sun protection.",
  "shopifyId": "9375060853013",
  "htmlId": "product-component-1753986308958",
  "category": "Home Gardening & DIY Kits",
  "countryOfOrigin": "China"
},
{
  "title": "Self-Watering Elevated Planter Box",
  "description": "Elevated planter features a built-in water reservoir, ensuring consistent hydration for flowers, vegetables, and herbs. Durable construction suits patios and balconies with minimal maintenance.",
  "shopifyId": "9375061344533",
  "htmlId": "product-component-1753971432415",
  "category": "Home Gardening & DIY Kits",
  "countryOfOrigin": "China"
},

{
  "title": "4-Pack 12-Cell Mini Indoor Propagation Greenhouses",
  "description": "Each pack includes four 12-chamber ABS propagation trays with adjustable vents, drainage holes and clear lids for optimal humidity control and easy seedling monitoring indoors.",
  "shopifyId": "9354744299797",
  "htmlId": "product-component-1753970533444",
  "category": "Home Gardening & DIY Kits",
  "countryOfOrigin": "China"
},
{
  "title": "8×8 ft Walk-In Polycarbonate Greenhouse with Double Doors",
  "description": "Heavy-duty aluminum frame and clear twin-wall polycarbonate panels with double doors, raised base and ground anchors. All-season protection for seedlings, vegetables and ornamental plants.",
  "shopifyId": "9375060263189",
  "htmlId": "product-component-1753970165020",
  "category": "Greenhouse Tools",
  "countryOfOrigin": "China"
},
{
  "title": "4-Pack Automatic Poultry Waterer Cups",
  "description": "Set of four durable plastic water cups supplies constant fresh water to chickens, ducks and other poultry. Easy to install on buckets or piping for low-maintenance coop hydration.",
  "shopifyId": "9347302588693",
  "htmlId": "product-component-1753937102467",
  "category": "Poultry Farming Supplies",
  "countryOfOrigin": "China"
},
{
  "title": "4ft Galvanized Sheep Wire Mesh Fence Roll",
  "description": "165 ft×4 ft hinge-joint woven galvanized steel mesh for durable livestock fencing. Hot-dip galvanized finish resists rust and provides secure containment for sheep and farm animals.",
  "shopifyId": "9375060066581",
  "htmlId": "product-component-1753936839366",
  "category": "Livestock Farming Supplies",
  "countryOfOrigin": "China"
},
{
  "title": "360° Rotating Garden Mobile Work Stool",
  "description": "High-carbon steel frame and PP cushion support up to 200 kg. Rotates 360° for easy greenhouse, garden, and orchard work at comfortable height.",
  "shopifyId": "9355182965013",
  "htmlId": "product-component-1753936580753",
  "category": "Farming Tools",
  "countryOfOrigin": "China"
},
{
  "title": "Large 47×18×18\" Metal Rectangular Planter",
  "description": "Durable metal planter box with built-in shelves and drainage holes. Spacious 47×18×18” design supports tall flowers and plants, ideal for patios, balconies, and garden displays.",
  "shopifyId": "9375061311765",
  "htmlId": "product-component-1753936298352",
  "category": "Home Gardening & DIY Kits",
  "countryOfOrigin": "China"
},

{
  "title": "2-Tier Foldable Wooden Cold Frame Greenhouse",
  "description": "Portable wooden cold frame with two shelves and clear plastic cover, protecting seedlings and extending growing season. Foldable design for easy storage on patio or raised planter beds.",
  "shopifyId": "9375060787477",
  "htmlId": "product-component-1753935843044",
  "category": "Greenhouse Tools",
  "countryOfOrigin": "China"
},

{
  "title": "23-Gauge Galvanized Hardware Cloth Roll – 24×50 ft",
  "description": "Durable 0.6 mm galvanized iron welded mesh (23 gauge) with ½″ square openings. Ideal for hog fencing, greenhouse flooring, and crawl space covers. Rust-resistant and flexible for easy use.",
  "shopifyId": "9375060885781",
  "htmlId": "product-component-1753918748120",
  "category": "Maintenance & Repair",
  "countryOfOrigin": "China"
},

{
  "title": "Clear PE Greenhouse Film Cover (3×4/3×6/3×10 m)",
  "description": "UV-resistant 0.04 mm PE sheeting in 3×4 m, 3×6 m or 3×10 m sizes. Waterproof, tear-proof cover protects plants from weather, frost and pests, and extends your growing season. Easy to install and fold away.",
  "shopifyId": "9354744201493",
  "htmlId": "product-component-1753918441155",
  "category": "Greenhouse Tools",
  "countryOfOrigin": "China"
},
{
  "title": "23-Gauge Galvanized Hardware Cloth Roll – 48×100 ft",
  "description": "Heavy-duty 0.6 mm welded mesh roll (23 gauge) resists rust for fencing, greenhouse flooring, and crawl space covers. Flexible yet sturdy galvanized iron wire with square ½″ openings.",
  "shopifyId": "9375060820245",
  "htmlId": "product-component-1753917708605",
  "category": "Maintenance & Repair",
  "countryOfOrigin": "China"
},
{
  title: "Digital Circulated Air Incubators with Auto Egg Turner 2450",
  description: "40W, Pro Incubator, Digital Display Shows Temperature, Humidity, & Days To Hatch, Incutek Heater Is Fast & Accurate, Heating To Factory Pre-Set Temperature Of 100 Degrees Fahrenheit Within Minutes, Days To Hatch Count Down, Set At 21 Days & Adjustable.",

  shopifyId: "", // ليس ضرورياً حالياً
  htmlId: "product-component-farm4250",
  category: "Incubators & Accessories",
  countryOfOrigin: "usa",
  price: "00.00",
  currency: "$",
 gallery: [
  "https://mrosupreme.com/cdn/shop/files/5508866_akceyb.jpg?v=1717836998&width=800",
  "https://m.media-amazon.com/images/I/71fR3qKVx+L._AC_SL1500_.jpg",
  "https://m.media-amazon.com/images/S/aplus-media-library-service-media/06454ced-159e-4549-922c-d94f5f61ef1a.__CR0,4,3000,1856_PT0_SX970_V1___.jpg",
  "https://m.media-amazon.com/images/S/aplus-media-library-service-media/61156469-3551-47dc-99b3-0fb400283e27.__CR0,7,3000,1856_PT0_SX970_V1___.jpg",
  "https://m.media-amazon.com/images/S/aplus-media-library-service-media/71d5cbed-18af-4449-a46c-330752630275.__CR0,0,1086,1359_PT0_SX362_V1___.jpg",
  "https://m.media-amazon.com/images/S/aplus-media-library-service-media/76ebdde7-82f0-41d9-9d0b-b5e9f89f102d.__CR0,0,1086,1359_PT0_SX362_V1___.jpg",
  "https://m.media-amazon.com/images/S/aplus-media-library-service-media/5a873b97-a04d-4513-ab06-a23cdd126e08.__CR0,0,1086,1359_PT0_SX362_V1___.jpg"
],
image: "https://mrosupreme.com/cdn/shop/files/5508866_akceyb.jpg?v=1717836998&width=800",
fullSizeImage: "",

  viewTitle: "Farm Innovators Pro 4250 Digital Egg Incubator",
  viewDescription: "This advanced incubator features a digital control center with automatic egg turning, designed to handle up to 41 chicken eggs. It provides precise temperature control (99.5°F to 100.5°F) and consistent airflow for optimal hatching conditions. Ideal for small farms and serious poultry enthusiasts.",
  specifications: "• Model: Pro Series 4250; • Power: 40W; • Egg Capacity: 41 chicken eggs; • Temperature Range: 99.5°F–100.5°F; • Auto Egg Turner: Included; • Origin: USA", checkoutType: "pastura" },
{
  "title": "Outdoor Furniture 30 Plants Home Gardening",
  "description": "*OUTDOOR OR INDOOR GROWING: Whether you grow indoors or in a sunny spot in your backyard or balcony, you can offer soil-free options for indoor and outdoor gardening with our Tower Hydroponics System.  With this self-watering home hydroponics system,...",
  "shopifyId": "9357056377109",
  "htmlId": "product-component-1751453346139",
  "category": "Smart & Sustainable Farming",
  "countryOfOrigin": "China", checkoutType: "shopify" },
  
{
  "title": "Moonspry Green Wood Nutrient Liquid Fertilizer",
  "description": "It can help to solve the problem of slow plant growth, stunted growth, short flowering period, vulnerable to plant diseases, help to solve the problem of slow plant growth, stunted growth, open, its use is very simple: ① hydroponics: each time into t...",
  "shopifyId": "9357056246037",
  "htmlId": "product-component-1751451051185",
  "category": "Home Gardening & DIY Kits",
  "countryOfOrigin": "China", checkoutType: "shopify" },
{
  "title": "Moonspry Concentrated Plant Food Spray for",
  "description": "It can formulate various nutrients needed for plant growth.  Its use is simple: Shake well before use: Make sure to mix well, spray the solution evenly over the plant to ensure complete coverage, and use this product weekly or every time you water it...",
  "shopifyId": "9357056442645",
  "htmlId": "product-component-1751452709799",
  "category": "Home Gardening & DIY Kits",
  "countryOfOrigin": "China", checkoutType: "shopify" },
{
  "title": "Black Metal Garden Arch Trellis 56.3×16.9×94.5\"",
  "description": "Powder-coated galvanized iron arch (56.3×16.9×94.5\") with pre-drilled assembly holes. Rust-resistant design supports roses, clematis and vines for elegant outdoor garden décor.",
  "shopifyId": "9357055754517",
  "htmlId": "product-component-1751226770948",
  "category": "Home Gardening & DIY Kits",
  "countryOfOrigin": "China", checkoutType: "shopify" },
{
  "title": "2L Portable Manual Milking Machine Kit",
  "description": "Stainless steel 2L bottle with strong suction and PU tubing delivers efficient, effort-saving milking. Transparent lid for fill-level monitoring, ideal for farms and dairy plants.",
  "shopifyId": "9356100043029",
  "htmlId": "product-component-1751139742494",
  "category": "Livestock Farming Supplies",
  "countryOfOrigin": "China", checkoutType: "shopify" },
{
  "title": "7ft Dark Brown Wooden Garden Arbor Arch",
  "description": "Durable fir wood arbor with metal fittings and trellis sides supports climbing plants and serves as an elegant wedding or party backdrop. Easy assembly for outdoor celebrations.",
  "shopifyId": "9357056344341",
  "htmlId": "product-component-1751130391836",
  "category": "Home Gardening & DIY Kits",
  "countryOfOrigin": "China", checkoutType: "shopify" },
{
  "title": "2-Pack Brown Iron Arch Garden Trellis 86.7×19.7\"",
  "description": "Two powder-coated iron trellises (86.7×19.7\") with pre-drilled holes for easy assembly. Rust-resistant finish and decorative bird & leaf accents support climbing roses, vines, peas and more.",
  "shopifyId": "9357056213269",
  "htmlId": "product-component-1751128940696",
  "category": "Home Gardening & DIY Kits",
  "countryOfOrigin": "China", checkoutType: "shopify" },
{
  "title": "2-Pack Cream White Metal Garden Trellis",
  "description": "Set of two 19.7×71\" galvanized, powder-coated steel trellises resists rust and supports climbing vines like roses, cucumbers, and beans. Easy assembly with pre-drilled holes.",
  "shopifyId": "9357056147733",
  "htmlId": "product-component-1751128049689",
  "category": "Home Gardening & DIY Kits",
  "countryOfOrigin": "China", checkoutType: "shopify" },
{
  "title": "1–3 Inch Polished River Rocks – 18 lb Decorative Stones",
  "description": "Eco-friendly, paraffin-polished river stones (1–3″, 18 lb) resist fading and retain moisture. Smooth, rounded edges suit pathways, planters, vases, aquariums, massage, and craft décor indoors or out.",
  "shopifyId": "9357056114965",
  "htmlId": "product-component-1751127598660",
  "category": "Home Gardening & DIY Kits",
  "countryOfOrigin": "China", checkoutType: "shopify" },
{
  "title": "1–3 Inch Polished River Rocks – 18 lb Decorative Stones",
  "description": "Natural, glossy 1–3″ river rocks (18 lb) add texture and color to garden beds, walkways, planters, and crafts. Smooth, durable, and fade-resistant for long-lasting outdoor or indoor décor.",
  "shopifyId": "9357056049429",
  "htmlId": "product-component-1751127098320",
  "category": "Home Gardening & DIY Kits",
  "countryOfOrigin": "China", checkoutType: "shopify" },
{
  "title": "1–3 Inch Polished River Rocks – 18 lb Decorative Stones",
  "description": "Natural, glossy 1–3″ river rocks (18 lb) add texture and color to garden beds, walkways, planters, and crafts. Smooth, durable, and fade-resistant for long-lasting outdoor or indoor décor.",
  "shopifyId": "9357056016661",
  "htmlId": "product-component-1751126667810",
  "category": "Home Gardening & DIY Kits",
  "countryOfOrigin": "China", checkoutType: "shopify" },
{
  "title": "50 ml Food-Grade Milking Collector Cup",
  "description": "Durable, non-toxic plastic collector holds 50 ml and fits standard goat and sheep milking systems for quick, hygienic milk collection on mobile carts or stationary units.",
  "shopifyId": "9356100337941",
  "htmlId": "product-component-1751104388238",
  "category": "Livestock Farming Supplies",
  "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Sheep Milking Machine Liner & Cup Accessory Set",
    "description": "Durable food-grade plastic liners and cups designed for sheep milking machines. Easy to install, they ensure gentle suction and hygienic milk collection for efficient dairy farming.",
    "shopifyId": "9356100403477",
    "htmlId": "product-component-1751087186356",
    "category": "Livestock Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Silicone Milking Suction Heads & Liners",
    "description": "Set of silicone liners and suction heads for manual or electric milking machines. Food-grade, durable, and easy to attach for hygienic, efficient milking of goats and sheep.",
    "shopifyId": "9356099977493",
    "htmlId": "product-component-1751086909975",
    "category": "Livestock Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Adjustable L80 Gas Pulsator for Milking Machines",
    "description": "Gas-driven pulsator with 50–180 ppm speed control and 60/40 pulsation ratio for optimal teat stimulation. Easy to install and durable, ensuring consistent, efficient milking performance.",
    "shopifyId": "9356100501781",
    "htmlId": "product-component-1751066573870",
    "category": "Livestock Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Adjustable L80 Gas Pulsator for Milking Machines",
    "description": "Durable gas-driven pulsator with 50–180 ppm speed control and 60/40 pulsation ratio. Easy to install, it maintains optimal teat stimulation for cows, goats, and sheep.",
    "shopifyId": "9356099944725",
    "htmlId": "product-component-1751057209050",
    "category": "Livestock Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "14-in-1 Stainless Steel Folding Multi-Tool",
    "description": "Lightweight stainless steel tool combines pliers, knife, scissors, screwdrivers and more in one foldable, safety-locking design. Ideal for DIY repairs, camping, fishing, and emergency EDC use.",
    "shopifyId": "9356100141333",
    "htmlId": "product-component-1751052403130",
    "category": "Maintenance & Repair",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "HP102 Dual-Outlet Milking Machine Pulsator",
    "description": "Adjustable-frequency pulsator creates periodic pressure for gentle, even milking. Durable plastic and metal construction with two outlets saves time and effort for cows, goats, and sheep.",
    "shopifyId": "9356100370709",
    "htmlId": "product-component-1751049688526",
    "category": "Livestock Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "5L Rechargeable Electric Pulsating Milking Machine",
    "description": "Automatic vacuum pump milker with bionic pulsation imitates calf suckling for gentle, efficient milking. Stainless steel bucket auto-stops when full, with thick silicone tubing for high-speed milk flow.",
    "shopifyId": "9356100469013",
    "htmlId": "product-component-1751049435507",
    "category": "Livestock Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Stainless Steel & Silicone Cow Milking Cluster Set",
    "description": "Rustproof stainless steel shell with soft silicone teat cups collects milk via vacuum pump. Durable, easy-to-clean cluster ensures gentle, efficient milking for cows and sheep.",
    "shopifyId": "9356100436245",
    "htmlId": "product-component-1751049158686",
    "category": "Livestock Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Classic Sheep & Goat Milking Cluster Assembly",
    "description": "Durable plastic, silicone and iron milking cluster fits standard goat and sheep machines. Provides balanced vacuum distribution for gentle, hygienic extraction and easy attachment during dairy operations.",
    "shopifyId": "9356100239637",
    "htmlId": "product-component-1751048925193",
    "category": "Livestock Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "7L Electric Vacuum Pulse Milking Machine",
    "description": "Adjustable-speed vacuum pump with pulse function automatically milks into a 7L stainless steel bucket. Soft silicone liner ensures gentle, hygienic extraction for goats, cows, and sheep.",
    "shopifyId": "9356100010261",
    "htmlId": "product-component-1751048689712",
    "category": "Livestock Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "5L Electric Goat & Cow Milking Machine",
    "description": "Gentle vacuum pump drains milk efficiently into a 5L stainless-steel can; adjustable suction protects teats, and durable non-toxic construction ensures easy cleaning and long-lasting home farm use.",
    "shopifyId": "9356099911957",
    "htmlId": "product-component-1751048470909",
    "category": "Livestock Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "5L Stainless Steel Electric Milking Machine",
    "description": "Automatic 5 L milker with adjustable vacuum pump and float shut-off. Stainless steel drum and silicone liners deliver efficient, hygienic milking for cows, goats, sheep, and other livestock.",
    "shopifyId": "9356100075797",
    "htmlId": "product-component-1751042070029",
    "category": "Livestock Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "50 ml Food-Grade Milking Collector Cup",
    "description": "Durable, non-toxic plastic milking claw cup holds 50 ml and fits standard goat and sheep milking machines for efficient, hygienic milk collection.",
    "shopifyId": "9356100534549",
    "htmlId": "product-component-1751017970784",
    "category": "Livestock Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "2-Pack Portable Goat & Sheep Milking Claw Kit",
    "description": "Includes two food-grade plastic milking teat cup assemblies with 41 cm tubing for manual or portable milking systems. Durable, non-toxic design streamlines milk collection for goats and sheep.",
    "shopifyId": "9356100108565",
    "htmlId": "product-component-1751017437044",
    "category": "Livestock Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "240 ml Plastic Milking Claw Collector",
    "description": "Food-grade plastic collector with four manifolds gathers up to 240 ml of milk per cycle. Compatible with mobile carts and milking systems for cows, goats, and sheep to streamline milk harvesting.",
    "shopifyId": "9356100174101",
    "htmlId": "product-component-1751016921305",
    "category": "Livestock Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Silicone Milking Liners for Cow & Sheep",
    "description": "Pair of food-grade silicone liners compatible with manual or electric milking machines. Soft, durable design ensures gentle suction and easy cleaning, ideal for cows, sheep, goats, and goats.",
    "shopifyId": "9356100272405",
    "htmlId": "product-component-1751016624026",
    "category": "Livestock Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "12V Electric Vacuum Milking Pump for Cows & Sheep",
    "description": "Adjustable-speed 12V pump with copper-core motor and ABS housing delivers gentle, efficient vacuum milking for cows, sheep, horses, and other livestock. Durable, corrosion-resistant, and easy to install.",
    "shopifyId": "9356100305173",
    "htmlId": "product-component-1751004623240",
    "category": "Livestock Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Manganese Steel Garden Hoe for Weeding",
    "description": "Forged manganese steel hoe head easily breaks soil, removes weeds, and trenches for planting vegetables and flowers; ergonomic design reduces fatigue and ensures long-lasting durability.",
    "shopifyId": "9355182670101",
    "htmlId": "product-component-1750949443972",
    "category": "Farming Tools",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Manganese Steel Small Garden Hoe for Soil Cultivation",
    "description": "Forged carbon-steel hoe head breaks up soil and removes weeds effortlessly for vegetable and flower planting. Lightweight and durable for efficient garden and outdoor farm tasks.",
    "shopifyId": "9355182473493",
    "htmlId": "product-component-1750948726695",
    "category": "Farming Tools",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Adjustable 5–8 Tine Ergonomic Garden Weeder",
    "description": "Durable alloy-steel weeder with 5–8 sharp tines and ergonomic handle loosens soil, pulls out roots, and makes weeding, trenching, and seedbed prep fast and labor-saving.",
    "shopifyId": "9355182604565",
    "htmlId": "product-component-1750948151596",
    "category": "Home Gardening & DIY Kits",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Manganese Steel Triangle Furrow Hoe",
    "description": "Forged triangular hoe head loosens soil, trenches, and removes weeds with an ultra-sharp blade. Ergonomic design reduces effort for efficient vegetable bed and garden maintenance.",
    "shopifyId": "9352654586133",
    "htmlId": "product-component-1750947144055",
    "category": "Farming Tools",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Durable Manganese Steel Planting Hoe",
    "description": "Forged manganese-steel blade breaks up soil and clears weeds effortlessly for vegetable and flower planting. Corrosion-resistant, lightweight design ensures long-lasting performance in home gardens and small farms.",
    "shopifyId": "9355182440725",
    "htmlId": "product-component-1750946778109",
    "category": "Farming Tools",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Carbon Steel Small Garden Hoe for Soil Cultivation",
    "description": "Forged manganese-steel hoe head easily breaks up soil and removes weeds for vegetable and flower planting. Lightweight and durable for efficient garden and outdoor farm use.",
    "shopifyId": "9355182473493",
    "htmlId": "product-component-1750945820363",
    "category": "Farming Tools",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Rolling Manual Cultivator & Soil Loosener",
    "description": "Durable manganese-steel cultivator with ten curved teeth in a rotating blade assembly. Simply insert and roll to efficiently weed, aerate, loosen soil, and prepare beds without heavy effort.",
    "shopifyId": "9355182571797",
    "htmlId": "product-component-1750945388484",
    "category": "Farming Tools",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Manganese Steel Survival Sapper Shovel Set",
    "description": "Heavy-duty 50 Mn steel shovel with red beech handle and protective cover—1.8 mm-thick head quenched to HRC 45–53. Ideal for camping, fishing, self-defense, and garden or farm tasks.",
    "shopifyId": "9355182702869",
    "htmlId": "product-component-1750869760969",
    "category": "Farming Tools",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Carbon Steel Small Garden Hoe for Weeding",
    "description": "Forged carbon steel hoe head easily loosens soil and clears weeds in vegetable beds and flower gardens. Durable, lightweight design reduces effort and ensures long-lasting performance.",
    "shopifyId": "9355182768405",
    "htmlId": "product-component-1750852721124",
    "category": "Farming Tools",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Labor-Saving Multi-Tooth Carbon Steel Garden Weeder",
    "description": "High-hardness carbon steel hoe with multi-tooth blade and ergonomic anti-slip handle effortlessly loosens soil and removes weeds in tight corners, potted plants, brick joints and garden beds.",
    "shopifyId": "9355182899477",
    "htmlId": "product-component-1750949811889",
    "category": "Home Gardening & DIY Kits",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "3-Piece Mini Metal & Wood Garden Tool Set",
    "description": "Compact shovel, harrow, and multi-function trowel crafted from durable metal and wood for efficient planting, soil mixing, and watering in pots or small garden beds.",
    "shopifyId": "9355182866709",
    "htmlId": "product-component-1750849010775",
    "category": "Home Gardening & DIY Kits",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "4-in-1 Ergonomic Garden Tool Set with Gloves",
    "description": "Durable magnesium-aluminum trowel, rake, cultivator and transplant tool feature depth markings and ergonomic handles for reduced fatigue. Includes two protective garden gloves for safe, efficient planting and weeding.",
    "shopifyId": "9355182833941",
    "htmlId": "product-component-1750848650933",
    "category": "Home Gardening & DIY Kits",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Four-Tooth Manganese Steel Soil Fork",
    "description": "Forged manganese-steel fork with four sharp tines effortlessly loosens, aerates, and clears soil manually. Ergonomic handle reduces fatigue during gardening and small-scale farm work.",
    "shopifyId": "9355182407957",
    "htmlId": "product-component-1750842001665",
    "category": "Farming Tools",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "5/10 ml Stainless Steel Continuous Injection Syringe",
    "description": "Durable stainless steel syringe delivers precise 5 ml or 10 ml vaccine doses continuously for poultry, pigs, sheep and cattle—quick, accurate inoculation with minimal waste.",
    "shopifyId": "9355182539029",
    "htmlId": "product-component-1750841477614",
    "category": "Livestock Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "2-in-1 Garden Aerator & Rotary Cultivator",
    "description": "Lightweight plastic tool with extended tines and removable middle wheel for deep soil aeration, scarifying, and row cultivation—ideal for healthy lawns and efficient garden prep.",
    "shopifyId": "9355182932245",
    "htmlId": "product-component-1750840940208",
    "category": "Farming Tools",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Veterinary Stainless Steel Surgical Scissors (14 cm)",
    "description": "Precision 14 cm stainless steel scissors with straight and curved tips for accurate animal procedures. Durable, corrosion-resistant design ensures easy cleaning and reliable performance in livestock care.",
    "shopifyId": "9355182735637",
    "htmlId": "product-component-1750840388223",
    "category": "Livestock Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Durable Forged Manganese Steel Garden Hoe",
    "description": "Hand-forged manganese steel blade with ergonomic handle for efficient weeding, soil digging, and planting. Built tough for outdoor gardens and small-scale farming, reducing wrist strain and lasting season after season.",
    "shopifyId": "9355182506261",
    "htmlId": "product-component-1750839943172",
    "category": "Farming Tools",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Hand-Forged Curved Blade Gardening Hoe",
    "description": "Blacksmith-forged steel hoe with ergonomic wooden handle and curved blade for effortless weeding, trenching, and soil cultivation. Built-in weight reduces wrist strain, ideal for home gardens and professional use.",
    "shopifyId": "9352654684437",
    "htmlId": "product-component-1750792999986",
    "category": "Home Gardening & DIY Kits",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Portable Tomato Greenhouse Grow Tent",
    "description": "Compact 56\u00d756\u00d756 cm PE mesh greenhouse protects tomatoes from wind and pests while enhancing photosynthesis. Easy assembly with wind-rope support offers a tear-resistant, durable cover for balconies.",
    "shopifyId": "9354744267029",
    "htmlId": "product-component-1750759887114",
    "category": "Greenhouse Tools",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Mini Indoor Propagation Greenhouse Tray",
    "description": "Durable plastic nursery box offers 12/24/48 pop-out cells, a water reservoir base, and vented transparent dome for optimal humidity control and easy seedling transplanting indoors.",
    "shopifyId": "9354744594709",
    "htmlId": "product-component-1750759465099",
    "category": "Home Gardening & DIY Kits",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Home Assistant Green Privacy-Focused Automation Hub",
    "description": "Open-source, energy-efficient smart home controller that runs locally\u2014no cloud needed. Seamlessly automate lights, climate, sensors, and security while keeping your data private and under your control.",
    "shopifyId": "9354744365333",
    "htmlId": "product-component-1750708710249",
    "category": "Smart & Sustainable Farming",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Solar-Powered Automatic Greenhouse Vent Opener",
    "description": "Aluminum-alloy vent opener uses solar heat to expand and open up to 45 cm as temperatures rise, then closes as they fall\u2014maintaining optimal greenhouse climate without electricity.",
    "shopifyId": "9354744463637",
    "htmlId": "product-component-1750708178839",
    "category": "Greenhouse Tools",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "12-Cell Seed Starter Tray with Adjustable Vent",
    "description": "12 flexible TPE pop-out cells with adjustable vents and clear cover ensure proper humidity and easy pop-out transplanting for healthy seedling growth.",
    "shopifyId": "9354744430869",
    "htmlId": "product-component-1750707790095",
    "category": "Home Gardening & DIY Kits",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Fiberglass Greenhouse Plant Hoop Set",
    "description": "Reusable fibreglass hoops with connectors form sturdy plant tunnels for seedling protection, frost cover or vine support in garden beds and raised planters.",
    "shopifyId": "9354744103189",
    "htmlId": "product-component-1750707320062",
    "category": "Greenhouse Tools",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Fiberglass Garden Hoop Tunnel Kit",
    "description": "Reusable bendable fiberglass hoops with galvanized joints and clips for creating plant tunnels that protect crops, support vines, and promote growth in raised beds.",
    "shopifyId": "9354744234261",
    "htmlId": "product-component-1750679352115",
    "category": "Greenhouse Tools",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Portable Walk-In Garden Greenhouse with Door",
    "description": "Quick-assemble walk-in greenhouse with roll-up door and waterproof PVC cover protects plants from frost, wind and pests year-round for outdoor or patio use.",
    "shopifyId": "9354744496405",
    "htmlId": "product-component-1750679005054",
    "category": "Greenhouse Tools",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Clear PE Greenhouse Insulation Cover with Zipper Door",
    "description": "Tear-proof 0.04 mm PE sheeting fits 2\u00d76 m or 2\u00d710 m frames, offering waterproof, UV-resistant thermal insulation and a roll-up zippered door for easy access and ventilation.",
    "shopifyId": "9354744168725",
    "htmlId": "product-component-1750673661202",
    "category": "Greenhouse Tools",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Clear PE Greenhouse Film Cover",
    "description": "Tear-proof, UV-resistant 0.04 mm PE sheeting fits 2 \u00d7 6 m or 2 \u00d7 10 m frames; waterproof and insulating with roll-up access for extended growing seasons.",
    "shopifyId": "9354744070421",
    "htmlId": "product-component-1750672464590",
    "category": "Greenhouse Tools",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "DIY 10\u201330M Micro Drip Irrigation Kit",
    "description": "Complete drip system with adjustable drippers, 10\u201330m hose, and connectors for automated, water-efficient garden or greenhouse irrigation.",
    "shopifyId": "9354744398101",
    "htmlId": "product-component-1750672197482",
    "category": "Irrigation Systems",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Green Plastic Vine Climbing Support Frame",
    "description": "Durable semicircle support rods hold vines and climbing plants securely in pots or garden beds, promoting healthy vertical growth and tidy plant arrangement.",
    "shopifyId": "9354744332565",
    "htmlId": "product-component-1750670983992",
    "category": "Home Gardening & DIY Kits",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Green Leaf Privacy Fence Panels \u2013 Decorative Outdoor Screen",
    "description": "Modular 50\u00d750 cm panels of UV-resistant plastic and silk cloth mimic lush foliage to create instant privacy, block wind, and enhance garden, patio or event d\u00e9cor with easy snap-in installation..",
    "shopifyId": "9354744135957",
    "htmlId": "product-component-1750670116547",
    "category": "Home Gardening & DIY Kits",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Thermal Insulation PE Greenhouse Cover with Zippered Door",
    "description": "Durable, tear-proof PE cover with >3000 mm waterproof rating, thermal insulation properties, and roll-up zippered door for easy access and ventilation. Fits 143 \u00d7 143 \u00d7 195 cm frames.",
    "shopifyId": "9354744660245",
    "htmlId": "product-component-1750669703553",
    "category": "Greenhouse Tools",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Green Inflatable Two-Room Family Camping Tent",
    "description": "Quick-inflate four-season tent with two separate sleeping chambers, >3000 mm waterproof fabric, integrated PVC air beams, and mesh windows for ventilation and insect protection. Ideal for family outdoor adventures..",
    "shopifyId": "9354744561941",
    "htmlId": "product-component-1750669163497",
    "category": "Greenhouse Tools",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Pop-Up Walk-In Greenhouse with Shelves",
    "description": "Assembles in minutes without tools; durable PVC cover, zip-up door, and four shelves provide year-round seedling protection and organization for indoor or outdoor gardening.",
    "shopifyId": "9354744627477",
    "htmlId": "product-component-1750667656861",
    "category": "Greenhouse Tools",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "21V Cordless Mini Electric Tiller",
    "description": "Drills 15cm deep and 21cm wide instantly, with safety-switch and splash guard protection for quick soil cultivation in small gardens and raised beds.",
    "shopifyId": "9352654651669",
    "htmlId": "product-component-1750235103925",
    "category": "Farming Tools",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "5-in-1 Garden Hand Tool Set",
    "description": "Includes shovel, trowel, rake, cultivator and weeder with ergonomic grips for effortless digging, planting, weeding and bonsai care in home gardens.",
    "shopifyId": "9345488781589",
    "htmlId": "product-component-1750230669531",
    "category": "Home Gardening & DIY Kits",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "High-Carbon Steel Rake & Shovel",
    "description": "Single-tooth rake and integrated shovel blade scrape manure, remove snow, and tackle farm tasks with corrosion-resistant high-carbon steel strength.",
    "shopifyId": "9352654782741",
    "htmlId": "product-component-1750154590629",
    "category": "Farming Tools",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Manganese Steel Triangle Furrow Hoe",
    "description": "Ultra-sharp forged steel blade loosens soil, trenches and removes weeds effortlessly for healthy vegetable beds with minimal physical strain.",
    "shopifyId": "9352654815509",
    "htmlId": "product-component-1750118249737",
    "category": "Farming Tools",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "DIY Rainproof Gravity Feeder Port",
    "description": "Installs in minutes on buckets or bins using the included hole saw, providing dry, gravity-fed feed to reduce spills and waste effectively.",
    "shopifyId": "9347302818069",
    "htmlId": "product-component-1750103712423",
    "category": "Poultry Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Automatic Free-Range Poultry Waterer",
    "description": "Gravity-fed bowl refills automatically to keep quails, ducks and chickens hydrated with minimal waste and simple cage attachment.",
    "shopifyId": "9347302719765",
    "htmlId": "product-component-1750103324009",
    "category": "Poultry Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "21V Cordless Electric Pruning Shears",
    "description": "Ergonomic cordless shears deliver precise cuts up to 25mm branches with effortless one-handed operation, perfect for hedges and shrub maintenance.",
    "shopifyId": "9344703529237",
    "htmlId": "product-component-1748618183129",
    "category": "Farming Tools",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Clear Acrylic Automatic Bird Feeder",
    "description": "Transparent acrylic feeder mounts inside or outside cages to prevent spillage and ensure continuous feeding for parrots, pigeons and chickens.",
    "shopifyId": "9347302916373",
    "htmlId": "product-component-1750099216252",
    "category": "Poultry Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Automatic 10-Egg Poultry Incubator",
    "description": "Auto-turning incubator holds ten eggs, controls temperature and humidity precisely, with removable tray and LED egg candler for easy monitoring.",
    "shopifyId": "9347302621461",
    "htmlId": "product-component-1750098830831",
    "category": "Incubators & Accessories",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "DIY Farm Henhouse & Rabbit Nest Kit",
    "description": "Interactive DIY model kit includes henhouse, rabbit nest and accessories for creative assembly, boosting fine motor skills and farm awareness.",
    "shopifyId": "9352654749973",
    "htmlId": "product-component-1750098494401",
    "category": "Home Gardening & DIY Kits",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Forged Steel Triangle Furrow Hoe",
    "description": "Forged steel hoe head with triangular blade loosens and aerates soil quickly, making trenching and weeding efficient for home gardens.",
    "shopifyId": "9352654717205",
    "htmlId": "product-component-1750098142967",
    "category": "Farming Tools",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Hand-Forged Triangle Furrow Hoe",
    "description": "Blacksmith-crafted hoe with ergonomic handle and sharp triangular blade for precise soil cultivation, weeding and trenching in small plots.",
    "shopifyId": "9352654848277",
    "htmlId": "product-component-1750093834244",
    "category": "Farming Tools",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Programmable Chicken Coop Door",
    "description": "Eco-friendly plastic coop door opens and closes on a timer to automate ventilation and security, simplifying poultry management routines.",
    "shopifyId": "9352654553365",
    "htmlId": "product-component-1750087052901",
    "category": "Smart & Sustainable Farming",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Automatic Livestock Water Bowl",
    "description": "PP water bowl with float valve auto-refill maintains consistent water levels, suitable for cattle, sheep, goats and pigs in barns or pens.",
    "shopifyId": "9352654618901",
    "htmlId": "product-component-1750086587760",
    "category": "Livestock Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "4-Egg Mini ABS Incubator",
    "description": "Compact ABS incubator holds four eggs with auto temp and humidity control, quiet operation and transparent lid for real-time hatching view.",
    "shopifyId": "9347303080213",
    "htmlId": "product-component-1750073050878",
    "category": "Incubators & Accessories",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Electric Handheld Feather Plucker",
    "description": "Handheld plucker uses soft rubber pins to gently remove feathers from poultry, combining powerful motor speed with lightweight portability.",
    "shopifyId": "9347302523157",
    "htmlId": "product-component-1750072281604",
    "category": "Poultry Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "PTC Poultry Drinker Heating Plate",
    "description": "Aluminum-plastic heating plate keeps water ice-free to \u201330\u00b0C using efficient PTC technology, ensuring safe, winter hydration for birds.",
    "shopifyId": "9347302785301",
    "htmlId": "product-component-1750071347288",
    "category": "Poultry Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Automatic Feeder & Waterer Combo",
    "description": "Integrated feeder and waterer buckets provide continuous feed and hydration with adjustable outlets to reduce waste and improve flock health.",
    "shopifyId": "9347303112981",
    "htmlId": "product-component-1750062492395",
    "category": "Starter Kits & Bundles",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Electric 56-Egg Turning Tray",
    "description": "Durable plastic egg turning tray holds 56 eggs and rotates automatically for even incubation and higher hatch rates in large-scale operations.",
    "shopifyId": "9347302654229",
    "htmlId": "product-component-1749327827331",
    "category": "Incubators & Accessories",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Anti-Peck Chicken Glasses (50pcs)",
    "description": "Pack of 50 lightweight protective glasses prevents pecking injuries and stress, improving flock health without restricting bird movement.",
    "shopifyId": "9347303047445",
    "htmlId": "product-component-1749327305231",
    "category": "Poultry Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "DIY Rainproof Feeder Ports (Set of 4)",
    "description": "Four gravity feeder ports with silicone seals and hole saw included, enabling quick DIY installation on barrels or bins for mess-free feeding.",
    "shopifyId": "9347303014677",
    "htmlId": "product-component-1749191767810",
    "category": "Poultry Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Smart 36-Egg Incubator",
    "description": "Wi-Fi enabled incubator holds 36 eggs with auto-turn, digital temp/humidity control and app alerts for hassle-free, high-yield hatching.",
    "shopifyId": "9347302850837",
    "htmlId": "product-component-1749189419452",
    "category": "Incubators & Accessories",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Infrared Poultry Heat Lamp",
    "description": "Durable infrared lamp provides consistent warmth to chicks and poults, improving survival rates and encouraging healthy growth in brooding areas.",
    "shopifyId": "9347302490389",
    "htmlId": "product-component-1749185297484",
    "category": "Poultry Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Flip-Top Plastic Chicken Feeder",
    "description": "Durable flip-top feeder holds up to 5kg feed, reduces spillage and allows easy refill and cleaning for backyard flocks.",
    "shopifyId": "9347302981909",
    "htmlId": "product-component-1749183766666",
    "category": "Poultry Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Chick Drinking Bucket",
    "description": "High-quality plastic bucket with nipple drinkers provides clean, nipple-fed hydration for chicks to support healthy early growth.",
    "shopifyId": "9347302949141",
    "htmlId": "product-component-1749157388339",
    "category": "Poultry Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Automatic Poultry Water Jug",
    "description": "High-capacity plastic jug with float valve delivers constant fresh water, minimizing maintenance and ensuring optimal hydration for flocks.",
    "shopifyId": "9347302555925",
    "htmlId": "product-component-1749156216581",
    "category": "Poultry Farming Supplies",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Multi-Teeth Weeding Tool",
    "description": "Carbon steel harrow with multiple tines efficiently removes weeds and aerates soil in fields and garden beds for improved crop health.",
    "shopifyId": "9345488716053",
    "htmlId": "product-component-1749142682319",
    "category": "Farming Tools",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Triangle Hoe",
    "description": "Compact manual plow with triangular blade cuts through tough soil and weeds, ideal for precise gardening and small farm tasks.",
    "shopifyId": "9345488748821",
    "htmlId": "product-component-1749117798508",
    "category": "Farming Tools",
    "countryOfOrigin": "China", checkoutType: "shopify" },
{
    "title": "Garden Shovel & Hand Tool Set",
    "description": "Includes trowel, mini shovel and cultivator heads on ergonomic handles for planting, weeding and loosening soil in raised beds and pots.",
    "shopifyId": "9343123292437",
    "htmlId": "product-component-1749138348381",
    "category": "Home Gardening & DIY Kits",
    "countryOfOrigin": "China", checkoutType: "shopify" }
];